Unittests init
JPA-ECM3440/ECM3440-residential-iot1 pull request #12
Opened 2021-09-30 08:46 UTC by jdday

2021-09-30 15:24 UTC, CallumTarttelin requested changes

2021-09-30 15:24 UTC, CallumTarttelin commented on soil-moisture-sensor/app_class.py
> +    with open('connection_string.txt', 'r') as file:
Just use `os.getEnv` and an environment variable

2021-09-30 15:24 UTC, CallumTarttelin commented on soil-moisture-sensor/app_class.py
> +    if os.getenv('PROD') == 'TRUE':
Surely the sensors just fail outside of prod? What is non prod behaviour?

2021-09-30 15:24 UTC, CallumTarttelin commented on soil-moisture-sensor/app_class.py
> +        print(dir(Message))
weird thing to print

2021-09-30 15:24 UTC, CallumTarttelin commented on soil-moisture-sensor/test_app.py
> +    mock_adc = MagicMock()
Consider using spec=...

2021-09-30 15:24 UTC, CallumTarttelin commented on soil-moisture-sensor/test_app.py
> +def test_connect(mock_iot_hub_device_client):
what an unnecessarily long name, `mock_client` should do or something similar

2021-10-04 11:10 UTC, CallumTarttelin commented
Also why is `app_class.py` a thing, we should just have one app

2021-10-04 11:17 UTC, jdday commented on soil-moisture-sensor/test_app.py
> +def test_handle_request(mock_method_response):
-- Split up relay on/off

2021-10-05 13:58 UTC, CallumTarttelin requested changes

2021-11-10 22:11 UTC, CallumTarttelin approved these changes

2021-11-10 22:15 UTC, merged